  # You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  name:
    app:                  DEPARTAMENTO DE GEOGRAFIA - UNIVERSIDADE DE SÃO PAULO
  name_app:               DEPARTAMENTO DE GEOGRAFIA - UNIVERSIDADE DE SÃO PAULO
  directory_productos:        %sf_upload_dir%/productos/
  allowed_mime_types:
    uploads: [application/pdf]
  email:
    administrador:       "info@crismoe.com.br"
    default_sender:      "noresponder@crismoe.com.br"
  msn:
    requerido:            Este campo é obrigatório
    save_confir:          Registro salvo com sucesso
    delete_confir:        Registro deletado com sucesso
    perfil_confir:        Associado ao perfil de usuário
        
  image:
    help:                <img  src="../images/help.png" align="left" />
    size:                 10485760
    size_text:            '10 MB'
    size_max:             3145728
    max_width:            980
    min_width:            980
    max_height:           305
    min_height:           280    
    cantidad_maxima:     12
  txt:
    size:                 2097152
    size_text:            '2 MB'
    size_max:             2097152
  pdf:
    help:                <img  src="../images/help.png" align="left" />
    size:                 3145728
    size_text:            '250 Kb'
    size_max:             3145728

  #Image per  module configuration
  upload_images:
    #newsPlugin image configuration.
    news:
      copies:   4
      size_1:   {pref_1: big, image_width_1: 750, image_height_1: 563}
      size_2:   {pref_2: medium, image_width_2: 464, image_height_2: 348}
      size_3:   {pref_3: small, image_width_3: 232, image_height_3: 174}
      size_4:   {pref_4: min, image_width_4: 84, image_height_4: 63}
    
    eventos:
      copies:   4
      size_1:   {pref_1: big, image_width_1: 750, image_height_1: 563}
      size_2:   {pref_2: medium, image_width_2: 464, image_height_2: 348}
      size_3:   {pref_3: small, image_width_3: 232, image_height_3: 174}
      size_4:   {pref_4: min, image_width_4: 84, image_height_4: 63}
  
    cliente:
      copies:   1
      size_1:   {pref_1: cte, image_width_1: 150, image_height_1: 150}
    
    producto:
      copies:   3
      size_1:   {pref_1: big, image_width_1: 392, image_height_1: 250}
      size_2:   {pref_2: med, image_width_2: 196, image_height_2: 127}
      size_3:   {pref_3: min, image_width_3: 140, image_height_3: 140}
      
    lxaccount:
      fileload: 1
      copies:   3
      size_1:   {pref_1: small, image_width_1: 28, image_height_1: 24}
      size_2:   {pref_2: med, image_width_2: 52, image_height_2: 52}
      size_3:   {pref_3: big, image_width_3: 94, image_height_3: 90}
    
    docente:
      fileload: 1
      copies:   3
      size_1:   {pref_1: small, image_width_1: 95, image_height_1: 60}
      size_2:   {pref_2: med, image_width_2: 185, image_height_2: 170}
      size_3:   {pref_3: big, image_width_3: 350, image_height_3: 315}
