<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/13 12:37:44
sfConfig::add(array(
  'mod_language_enabled' => true,
  'mod_language_view_class' => 'sfPHP',
  'mod_language_msn_ayuda' => '<img  src="/sf/sf_admin/images/help.png" align="left" />&nbsp;Para evitar errores en el sistema, aseg&uacute;rese que la selecci&oacute;n de idioma y pa&iacute;s sea la correcta.',
  'mod_language_msn_error_no_status' => '<img  src="/sf/sf_admin/images/error.png" align="left" />
&nbsp;Your changes have been made. &nbsp;The language can not be disabled.
',
  'mod_language_msn_error_status_desactivo' => 'The language can\'t be disabled.',
  'mod_language_msn_error_language_principal' => 'This language is principal.',
  'mod_language_msn_error_culture_duplicate' => '<img  src="/sf/sf_admin/images/error.png" align="left" />&nbsp;Error de duplicidad al guardar idioma.',
  'mod_language_msn_leyenda' => '<img  src="/sf/sf_admin/images/1.png" align="left" /> <img  src="/sf/sf_admin/images/0.png" align="left" />&nbsp; Definir idioma como principal<br>
',
  'mod_language_msn_idioma_base' => '<img  src="/sf/sf_admin/images/error.png" align="left" />&nbsp;No esta permitido borrar el idioma base del sistema.',
));
