<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/10/13 12:37:44
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_delete',
    ),
  ),
  'changestatus' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_update',
    ),
  ),
  'deleteimage' => 
  array (
    'credentials' => 
    array (
      0 => 'language_view',
      1 => 'language_update',
    ),
  ),
);
