<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/10 11:00:54
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'semestre_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'semestre_view',
      1 => 'semestre_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'semestre_view',
      1 => 'semestre_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'semestre_view',
      1 => 'semestre_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'semestre_view',
      1 => 'semestre_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'semestre_view',
      1 => 'semestre_delete',
    ),
  ),
);
