<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/04/15 14:56:33
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'banner_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'banner_view',
      1 => 'banner_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'banner_view',
      1 => 'banner_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'banner_view',
      1 => 'banner_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'banner_view',
      1 => 'banner_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'banner_view',
      1 => 'banner_delete',
    ),
  ),
);
