<?php

/**
 * Base class that represents a row from the 'lojas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 17/10/2013 16:31:46
 *
 * @package    lib.model.geografia.om
 */
abstract class BaseLojas extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        LojasPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_loja field.
	 * @var        int
	 */
	protected $id_loja;

	/**
	 * The value for the id_estado field.
	 * @var        int
	 */
	protected $id_estado;

	/**
	 * The value for the id_ciudad field.
	 * @var        int
	 */
	protected $id_ciudad;

	/**
	 * The value for the tipo_loja field.
	 * @var        string
	 */
	protected $tipo_loja;

	/**
	 * The value for the nome_loja field.
	 * @var        string
	 */
	protected $nome_loja;

	/**
	 * The value for the endereco field.
	 * @var        string
	 */
	protected $endereco;

	/**
	 * The value for the numero field.
	 * @var        int
	 */
	protected $numero;

	/**
	 * The value for the complemento field.
	 * @var        string
	 */
	protected $complemento;

	/**
	 * The value for the telefone field.
	 * @var        string
	 */
	protected $telefone;

	/**
	 * The value for the celular field.
	 * @var        string
	 */
	protected $celular;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the site field.
	 * @var        string
	 */
	protected $site;

	/**
	 * The value for the status field.
	 * @var        int
	 */
	protected $status;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'LojasPeer';

	/**
	 * Get the [id_loja] column value.
	 * 
	 * @return     int
	 */
	public function getIdLoja()
	{
		return $this->id_loja;
	}

	/**
	 * Get the [id_estado] column value.
	 * 
	 * @return     int
	 */
	public function getIdEstado()
	{
		return $this->id_estado;
	}

	/**
	 * Get the [id_ciudad] column value.
	 * 
	 * @return     int
	 */
	public function getIdCiudad()
	{
		return $this->id_ciudad;
	}

	/**
	 * Get the [tipo_loja] column value.
	 * 
	 * @return     string
	 */
	public function getTipoLoja()
	{
		return $this->tipo_loja;
	}

	/**
	 * Get the [nome_loja] column value.
	 * 
	 * @return     string
	 */
	public function getNomeLoja()
	{
		return $this->nome_loja;
	}

	/**
	 * Get the [endereco] column value.
	 * 
	 * @return     string
	 */
	public function getEndereco()
	{
		return $this->endereco;
	}

	/**
	 * Get the [numero] column value.
	 * 
	 * @return     int
	 */
	public function getNumero()
	{
		return $this->numero;
	}

	/**
	 * Get the [complemento] column value.
	 * 
	 * @return     string
	 */
	public function getComplemento()
	{
		return $this->complemento;
	}

	/**
	 * Get the [telefone] column value.
	 * 
	 * @return     string
	 */
	public function getTelefone()
	{
		return $this->telefone;
	}

	/**
	 * Get the [celular] column value.
	 * 
	 * @return     string
	 */
	public function getCelular()
	{
		return $this->celular;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [site] column value.
	 * 
	 * @return     string
	 */
	public function getSite()
	{
		return $this->site;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Set the value of [id_loja] column.
	 * 
	 * @param      int $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setIdLoja($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_loja !== $v) {
			$this->id_loja = $v;
			$this->modifiedColumns[] = LojasPeer::ID_LOJA;
		}

		return $this;
	} // setIdLoja()

	/**
	 * Set the value of [id_estado] column.
	 * 
	 * @param      int $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setIdEstado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_estado !== $v) {
			$this->id_estado = $v;
			$this->modifiedColumns[] = LojasPeer::ID_ESTADO;
		}

		return $this;
	} // setIdEstado()

	/**
	 * Set the value of [id_ciudad] column.
	 * 
	 * @param      int $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setIdCiudad($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_ciudad !== $v) {
			$this->id_ciudad = $v;
			$this->modifiedColumns[] = LojasPeer::ID_CIUDAD;
		}

		return $this;
	} // setIdCiudad()

	/**
	 * Set the value of [tipo_loja] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setTipoLoja($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tipo_loja !== $v) {
			$this->tipo_loja = $v;
			$this->modifiedColumns[] = LojasPeer::TIPO_LOJA;
		}

		return $this;
	} // setTipoLoja()

	/**
	 * Set the value of [nome_loja] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setNomeLoja($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nome_loja !== $v) {
			$this->nome_loja = $v;
			$this->modifiedColumns[] = LojasPeer::NOME_LOJA;
		}

		return $this;
	} // setNomeLoja()

	/**
	 * Set the value of [endereco] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setEndereco($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->endereco !== $v) {
			$this->endereco = $v;
			$this->modifiedColumns[] = LojasPeer::ENDERECO;
		}

		return $this;
	} // setEndereco()

	/**
	 * Set the value of [numero] column.
	 * 
	 * @param      int $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setNumero($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->numero !== $v) {
			$this->numero = $v;
			$this->modifiedColumns[] = LojasPeer::NUMERO;
		}

		return $this;
	} // setNumero()

	/**
	 * Set the value of [complemento] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setComplemento($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->complemento !== $v) {
			$this->complemento = $v;
			$this->modifiedColumns[] = LojasPeer::COMPLEMENTO;
		}

		return $this;
	} // setComplemento()

	/**
	 * Set the value of [telefone] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setTelefone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefone !== $v) {
			$this->telefone = $v;
			$this->modifiedColumns[] = LojasPeer::TELEFONE;
		}

		return $this;
	} // setTelefone()

	/**
	 * Set the value of [celular] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setCelular($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->celular !== $v) {
			$this->celular = $v;
			$this->modifiedColumns[] = LojasPeer::CELULAR;
		}

		return $this;
	} // setCelular()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = LojasPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [site] column.
	 * 
	 * @param      string $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setSite($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->site !== $v) {
			$this->site = $v;
			$this->modifiedColumns[] = LojasPeer::SITE;
		}

		return $this;
	} // setSite()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      int $v new value
	 * @return     Lojas The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = LojasPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_loja = (isset($row[$startcol + 0]) && $row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_estado = (isset($row[$startcol + 1]) && $row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->id_ciudad = (isset($row[$startcol + 2]) && $row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->tipo_loja = (isset($row[$startcol + 3]) && $row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->nome_loja = (isset($row[$startcol + 4]) && $row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->endereco = (isset($row[$startcol + 5]) && $row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->numero = (isset($row[$startcol + 6]) && $row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->complemento = (isset($row[$startcol + 7]) && $row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->telefone = (isset($row[$startcol + 8]) && $row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->celular = (isset($row[$startcol + 9]) && $row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->email = (isset($row[$startcol + 10]) && $row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->site = (isset($row[$startcol + 11]) && $row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->status = (isset($row[$startcol + 12]) && $row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = LojasPeer::NUM_COLUMNS - LojasPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Lojas object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LojasPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = LojasPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LojasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseLojas:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				LojasPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseLojas:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LojasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseLojas:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseLojas:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				LojasPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = LojasPeer::ID_LOJA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = LojasPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdLoja($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += LojasPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = LojasPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = LojasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdLoja();
				break;
			case 1:
				return $this->getIdEstado();
				break;
			case 2:
				return $this->getIdCiudad();
				break;
			case 3:
				return $this->getTipoLoja();
				break;
			case 4:
				return $this->getNomeLoja();
				break;
			case 5:
				return $this->getEndereco();
				break;
			case 6:
				return $this->getNumero();
				break;
			case 7:
				return $this->getComplemento();
				break;
			case 8:
				return $this->getTelefone();
				break;
			case 9:
				return $this->getCelular();
				break;
			case 10:
				return $this->getEmail();
				break;
			case 11:
				return $this->getSite();
				break;
			case 12:
				return $this->getStatus();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = LojasPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdLoja(),
			$keys[1] => $this->getIdEstado(),
			$keys[2] => $this->getIdCiudad(),
			$keys[3] => $this->getTipoLoja(),
			$keys[4] => $this->getNomeLoja(),
			$keys[5] => $this->getEndereco(),
			$keys[6] => $this->getNumero(),
			$keys[7] => $this->getComplemento(),
			$keys[8] => $this->getTelefone(),
			$keys[9] => $this->getCelular(),
			$keys[10] => $this->getEmail(),
			$keys[11] => $this->getSite(),
			$keys[12] => $this->getStatus(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = LojasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdLoja($value);
				break;
			case 1:
				$this->setIdEstado($value);
				break;
			case 2:
				$this->setIdCiudad($value);
				break;
			case 3:
				$this->setTipoLoja($value);
				break;
			case 4:
				$this->setNomeLoja($value);
				break;
			case 5:
				$this->setEndereco($value);
				break;
			case 6:
				$this->setNumero($value);
				break;
			case 7:
				$this->setComplemento($value);
				break;
			case 8:
				$this->setTelefone($value);
				break;
			case 9:
				$this->setCelular($value);
				break;
			case 10:
				$this->setEmail($value);
				break;
			case 11:
				$this->setSite($value);
				break;
			case 12:
				$this->setStatus($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = LojasPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdLoja($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdEstado($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdCiudad($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTipoLoja($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNomeLoja($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEndereco($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNumero($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setComplemento($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTelefone($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCelular($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setEmail($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setSite($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setStatus($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(LojasPeer::DATABASE_NAME);

		if ($this->isColumnModified(LojasPeer::ID_LOJA)) $criteria->add(LojasPeer::ID_LOJA, $this->id_loja);
		if ($this->isColumnModified(LojasPeer::ID_ESTADO)) $criteria->add(LojasPeer::ID_ESTADO, $this->id_estado);
		if ($this->isColumnModified(LojasPeer::ID_CIUDAD)) $criteria->add(LojasPeer::ID_CIUDAD, $this->id_ciudad);
		if ($this->isColumnModified(LojasPeer::TIPO_LOJA)) $criteria->add(LojasPeer::TIPO_LOJA, $this->tipo_loja);
		if ($this->isColumnModified(LojasPeer::NOME_LOJA)) $criteria->add(LojasPeer::NOME_LOJA, $this->nome_loja);
		if ($this->isColumnModified(LojasPeer::ENDERECO)) $criteria->add(LojasPeer::ENDERECO, $this->endereco);
		if ($this->isColumnModified(LojasPeer::NUMERO)) $criteria->add(LojasPeer::NUMERO, $this->numero);
		if ($this->isColumnModified(LojasPeer::COMPLEMENTO)) $criteria->add(LojasPeer::COMPLEMENTO, $this->complemento);
		if ($this->isColumnModified(LojasPeer::TELEFONE)) $criteria->add(LojasPeer::TELEFONE, $this->telefone);
		if ($this->isColumnModified(LojasPeer::CELULAR)) $criteria->add(LojasPeer::CELULAR, $this->celular);
		if ($this->isColumnModified(LojasPeer::EMAIL)) $criteria->add(LojasPeer::EMAIL, $this->email);
		if ($this->isColumnModified(LojasPeer::SITE)) $criteria->add(LojasPeer::SITE, $this->site);
		if ($this->isColumnModified(LojasPeer::STATUS)) $criteria->add(LojasPeer::STATUS, $this->status);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(LojasPeer::DATABASE_NAME);

		$criteria->add(LojasPeer::ID_LOJA, $this->id_loja);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdLoja();
	}

	/**
	 * Generic method to set the primary key (id_loja column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdLoja($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Lojas (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdEstado($this->id_estado);

		$copyObj->setIdCiudad($this->id_ciudad);

		$copyObj->setTipoLoja($this->tipo_loja);

		$copyObj->setNomeLoja($this->nome_loja);

		$copyObj->setEndereco($this->endereco);

		$copyObj->setNumero($this->numero);

		$copyObj->setComplemento($this->complemento);

		$copyObj->setTelefone($this->telefone);

		$copyObj->setCelular($this->celular);

		$copyObj->setEmail($this->email);

		$copyObj->setSite($this->site);

		$copyObj->setStatus($this->status);


		$copyObj->setNew(true);

		$copyObj->setIdLoja(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Lojas Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     LojasPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new LojasPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseLojas:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseLojas::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseLojas
