<?php

/**
 * Base static class for performing query and update operations on the 'solicitud' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 17/10/2013 16:31:46
 *
 * @package    lib.model.geografia.om
 */
abstract class BaseSolicitudPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'solicitud';

	/** the related Propel class for this table */
	const OM_CLASS = 'Solicitud';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.geografia.Solicitud';

	/** the related TableMap class for this table */
	const TM_CLASS = 'SolicitudTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 42;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID_SOLICITUD field */
	const ID_SOLICITUD = 'solicitud.ID_SOLICITUD';

	/** the column name for the ID_SOLICITUD_TIPO field */
	const ID_SOLICITUD_TIPO = 'solicitud.ID_SOLICITUD_TIPO';

	/** the column name for the PROGRAMA field */
	const PROGRAMA = 'solicitud.PROGRAMA';

	/** the column name for the CURSO field */
	const CURSO = 'solicitud.CURSO';

	/** the column name for the NOME_COMPLETO field */
	const NOME_COMPLETO = 'solicitud.NOME_COMPLETO';

	/** the column name for the NUMERO_USO field */
	const NUMERO_USO = 'solicitud.NUMERO_USO';

	/** the column name for the MINISTRANTE field */
	const MINISTRANTE = 'solicitud.MINISTRANTE';

	/** the column name for the ORIENTADOR field */
	const ORIENTADOR = 'solicitud.ORIENTADOR';

	/** the column name for the EMAIL field */
	const EMAIL = 'solicitud.EMAIL';

	/** the column name for the MOTIVO_TRANCAMENTO field */
	const MOTIVO_TRANCAMENTO = 'solicitud.MOTIVO_TRANCAMENTO';

	/** the column name for the NIVEL field */
	const NIVEL = 'solicitud.NIVEL';

	/** the column name for the DATA_REALIZACAO field */
	const DATA_REALIZACAO = 'solicitud.DATA_REALIZACAO';

	/** the column name for the HORARIO field */
	const HORARIO = 'solicitud.HORARIO';

	/** the column name for the TITULO_TRABALHO field */
	const TITULO_TRABALHO = 'solicitud.TITULO_TRABALHO';

	/** the column name for the NUMERO_PAGINAS field */
	const NUMERO_PAGINAS = 'solicitud.NUMERO_PAGINAS';

	/** the column name for the SUGESTAO_BANCA field */
	const SUGESTAO_BANCA = 'solicitud.SUGESTAO_BANCA';

	/** the column name for the CPF_DO_ALUNO field */
	const CPF_DO_ALUNO = 'solicitud.CPF_DO_ALUNO';

	/** the column name for the TITULAR1 field */
	const TITULAR1 = 'solicitud.TITULAR1';

	/** the column name for the INSTITUCION1 field */
	const INSTITUCION1 = 'solicitud.INSTITUCION1';

	/** the column name for the ENDERECO1 field */
	const ENDERECO1 = 'solicitud.ENDERECO1';

	/** the column name for the TITULAR2 field */
	const TITULAR2 = 'solicitud.TITULAR2';

	/** the column name for the INSTITUCION2 field */
	const INSTITUCION2 = 'solicitud.INSTITUCION2';

	/** the column name for the ENDERECO2 field */
	const ENDERECO2 = 'solicitud.ENDERECO2';

	/** the column name for the ARQ_PLANO_TRABALHO field */
	const ARQ_PLANO_TRABALHO = 'solicitud.ARQ_PLANO_TRABALHO';

	/** the column name for the ARQ_JUSTIFICATIVA field */
	const ARQ_JUSTIFICATIVA = 'solicitud.ARQ_JUSTIFICATIVA';

	/** the column name for the ARQ_ORCAMENTO field */
	const ARQ_ORCAMENTO = 'solicitud.ARQ_ORCAMENTO';

	/** the column name for the ARQ_CURRICULO_LATTED field */
	const ARQ_CURRICULO_LATTED = 'solicitud.ARQ_CURRICULO_LATTED';

	/** the column name for the ARQ_PEDIDO_DO_INTERESSADO field */
	const ARQ_PEDIDO_DO_INTERESSADO = 'solicitud.ARQ_PEDIDO_DO_INTERESSADO';

	/** the column name for the ARQ_CREDENCIAMENTO field */
	const ARQ_CREDENCIAMENTO = 'solicitud.ARQ_CREDENCIAMENTO';

	/** the column name for the ARQ_PROF_EXTERNO field */
	const ARQ_PROF_EXTERNO = 'solicitud.ARQ_PROF_EXTERNO';

	/** the column name for the ARQ_CADASTRO_DOCENTE_EXTERNO field */
	const ARQ_CADASTRO_DOCENTE_EXTERNO = 'solicitud.ARQ_CADASTRO_DOCENTE_EXTERNO';

	/** the column name for the ARQ_CARTA_ALUNO field */
	const ARQ_CARTA_ALUNO = 'solicitud.ARQ_CARTA_ALUNO';

	/** the column name for the ARQ_MANIFESTACAO_ORIENTADOR field */
	const ARQ_MANIFESTACAO_ORIENTADOR = 'solicitud.ARQ_MANIFESTACAO_ORIENTADOR';

	/** the column name for the ARQ_CRONOGRAMA_ACTIVIDADES field */
	const ARQ_CRONOGRAMA_ACTIVIDADES = 'solicitud.ARQ_CRONOGRAMA_ACTIVIDADES';

	/** the column name for the ARQ_COPIA_TRABALHO field */
	const ARQ_COPIA_TRABALHO = 'solicitud.ARQ_COPIA_TRABALHO';

	/** the column name for the ARQ_COMPROBANTE field */
	const ARQ_COMPROBANTE = 'solicitud.ARQ_COMPROBANTE';

	/** the column name for the ARQ_TRANSFERENCA_ORIENTACAO field */
	const ARQ_TRANSFERENCA_ORIENTACAO = 'solicitud.ARQ_TRANSFERENCA_ORIENTACAO';

	/** the column name for the ARQ_TERMO_ORIENTADOR field */
	const ARQ_TERMO_ORIENTADOR = 'solicitud.ARQ_TERMO_ORIENTADOR';

	/** the column name for the ARQ_RELATORIO_QUALIFICACAO field */
	const ARQ_RELATORIO_QUALIFICACAO = 'solicitud.ARQ_RELATORIO_QUALIFICACAO';

	/** the column name for the ARQ_PROJETO_PESQUISA field */
	const ARQ_PROJETO_PESQUISA = 'solicitud.ARQ_PROJETO_PESQUISA';

	/** the column name for the ARQ_SOLICITACAO_BOLSA field */
	const ARQ_SOLICITACAO_BOLSA = 'solicitud.ARQ_SOLICITACAO_BOLSA';

	/** the column name for the STATUS field */
	const STATUS = 'solicitud.STATUS';

	/**
	 * An identiy map to hold any loaded instances of Solicitud objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Solicitud[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('IdSolicitud', 'IdSolicitudTipo', 'Programa', 'Curso', 'NomeCompleto', 'NumeroUso', 'Ministrante', 'Orientador', 'Email', 'MotivoTrancamento', 'Nivel', 'DataRealizacao', 'Horario', 'TituloTrabalho', 'NumeroPaginas', 'SugestaoBanca', 'CpfDoAluno', 'Titular1', 'Institucion1', 'Endereco1', 'Titular2', 'Institucion2', 'Endereco2', 'ArqPlanoTrabalho', 'ArqJustificativa', 'ArqOrcamento', 'ArqCurriculoLatted', 'ArqPedidoDoInteressado', 'ArqCredenciamento', 'ArqProfExterno', 'ArqCadastroDocenteExterno', 'ArqCartaAluno', 'ArqManifestacaoOrientador', 'ArqCronogramaActividades', 'ArqCopiaTrabalho', 'ArqComprobante', 'ArqTransferencaOrientacao', 'ArqTermoOrientador', 'ArqRelatorioQualificacao', 'ArqProjetoPesquisa', 'ArqSolicitacaoBolsa', 'Status', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('idSolicitud', 'idSolicitudTipo', 'programa', 'curso', 'nomeCompleto', 'numeroUso', 'ministrante', 'orientador', 'email', 'motivoTrancamento', 'nivel', 'dataRealizacao', 'horario', 'tituloTrabalho', 'numeroPaginas', 'sugestaoBanca', 'cpfDoAluno', 'titular1', 'institucion1', 'endereco1', 'titular2', 'institucion2', 'endereco2', 'arqPlanoTrabalho', 'arqJustificativa', 'arqOrcamento', 'arqCurriculoLatted', 'arqPedidoDoInteressado', 'arqCredenciamento', 'arqProfExterno', 'arqCadastroDocenteExterno', 'arqCartaAluno', 'arqManifestacaoOrientador', 'arqCronogramaActividades', 'arqCopiaTrabalho', 'arqComprobante', 'arqTransferencaOrientacao', 'arqTermoOrientador', 'arqRelatorioQualificacao', 'arqProjetoPesquisa', 'arqSolicitacaoBolsa', 'status', ),
		BasePeer::TYPE_COLNAME => array (self::ID_SOLICITUD, self::ID_SOLICITUD_TIPO, self::PROGRAMA, self::CURSO, self::NOME_COMPLETO, self::NUMERO_USO, self::MINISTRANTE, self::ORIENTADOR, self::EMAIL, self::MOTIVO_TRANCAMENTO, self::NIVEL, self::DATA_REALIZACAO, self::HORARIO, self::TITULO_TRABALHO, self::NUMERO_PAGINAS, self::SUGESTAO_BANCA, self::CPF_DO_ALUNO, self::TITULAR1, self::INSTITUCION1, self::ENDERECO1, self::TITULAR2, self::INSTITUCION2, self::ENDERECO2, self::ARQ_PLANO_TRABALHO, self::ARQ_JUSTIFICATIVA, self::ARQ_ORCAMENTO, self::ARQ_CURRICULO_LATTED, self::ARQ_PEDIDO_DO_INTERESSADO, self::ARQ_CREDENCIAMENTO, self::ARQ_PROF_EXTERNO, self::ARQ_CADASTRO_DOCENTE_EXTERNO, self::ARQ_CARTA_ALUNO, self::ARQ_MANIFESTACAO_ORIENTADOR, self::ARQ_CRONOGRAMA_ACTIVIDADES, self::ARQ_COPIA_TRABALHO, self::ARQ_COMPROBANTE, self::ARQ_TRANSFERENCA_ORIENTACAO, self::ARQ_TERMO_ORIENTADOR, self::ARQ_RELATORIO_QUALIFICACAO, self::ARQ_PROJETO_PESQUISA, self::ARQ_SOLICITACAO_BOLSA, self::STATUS, ),
		BasePeer::TYPE_FIELDNAME => array ('id_solicitud', 'id_solicitud_tipo', 'programa', 'curso', 'nome_completo', 'numero_uso', 'ministrante', 'orientador', 'email', 'motivo_trancamento', 'nivel', 'data_realizacao', 'horario', 'titulo_trabalho', 'numero_paginas', 'sugestao_banca', 'cpf_do_aluno', 'titular1', 'institucion1', 'endereco1', 'titular2', 'institucion2', 'endereco2', 'arq_plano_trabalho', 'arq_justificativa', 'arq_orcamento', 'arq_curriculo_Latted', 'arq_pedido_do_interessado', 'arq_credenciamento', 'arq_prof_externo', 'arq_cadastro_docente_externo', 'arq_carta_aluno', 'arq_manifestacao_orientador', 'arq_cronograma_actividades', 'arq_copia_trabalho', 'arq_comprobante', 'arq_transferenca_orientacao', 'arq_termo_orientador', 'arq_relatorio_qualificacao', 'arq_projeto_pesquisa', 'arq_solicitacao_bolsa', 'status', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('IdSolicitud' => 0, 'IdSolicitudTipo' => 1, 'Programa' => 2, 'Curso' => 3, 'NomeCompleto' => 4, 'NumeroUso' => 5, 'Ministrante' => 6, 'Orientador' => 7, 'Email' => 8, 'MotivoTrancamento' => 9, 'Nivel' => 10, 'DataRealizacao' => 11, 'Horario' => 12, 'TituloTrabalho' => 13, 'NumeroPaginas' => 14, 'SugestaoBanca' => 15, 'CpfDoAluno' => 16, 'Titular1' => 17, 'Institucion1' => 18, 'Endereco1' => 19, 'Titular2' => 20, 'Institucion2' => 21, 'Endereco2' => 22, 'ArqPlanoTrabalho' => 23, 'ArqJustificativa' => 24, 'ArqOrcamento' => 25, 'ArqCurriculoLatted' => 26, 'ArqPedidoDoInteressado' => 27, 'ArqCredenciamento' => 28, 'ArqProfExterno' => 29, 'ArqCadastroDocenteExterno' => 30, 'ArqCartaAluno' => 31, 'ArqManifestacaoOrientador' => 32, 'ArqCronogramaActividades' => 33, 'ArqCopiaTrabalho' => 34, 'ArqComprobante' => 35, 'ArqTransferencaOrientacao' => 36, 'ArqTermoOrientador' => 37, 'ArqRelatorioQualificacao' => 38, 'ArqProjetoPesquisa' => 39, 'ArqSolicitacaoBolsa' => 40, 'Status' => 41, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('idSolicitud' => 0, 'idSolicitudTipo' => 1, 'programa' => 2, 'curso' => 3, 'nomeCompleto' => 4, 'numeroUso' => 5, 'ministrante' => 6, 'orientador' => 7, 'email' => 8, 'motivoTrancamento' => 9, 'nivel' => 10, 'dataRealizacao' => 11, 'horario' => 12, 'tituloTrabalho' => 13, 'numeroPaginas' => 14, 'sugestaoBanca' => 15, 'cpfDoAluno' => 16, 'titular1' => 17, 'institucion1' => 18, 'endereco1' => 19, 'titular2' => 20, 'institucion2' => 21, 'endereco2' => 22, 'arqPlanoTrabalho' => 23, 'arqJustificativa' => 24, 'arqOrcamento' => 25, 'arqCurriculoLatted' => 26, 'arqPedidoDoInteressado' => 27, 'arqCredenciamento' => 28, 'arqProfExterno' => 29, 'arqCadastroDocenteExterno' => 30, 'arqCartaAluno' => 31, 'arqManifestacaoOrientador' => 32, 'arqCronogramaActividades' => 33, 'arqCopiaTrabalho' => 34, 'arqComprobante' => 35, 'arqTransferencaOrientacao' => 36, 'arqTermoOrientador' => 37, 'arqRelatorioQualificacao' => 38, 'arqProjetoPesquisa' => 39, 'arqSolicitacaoBolsa' => 40, 'status' => 41, ),
		BasePeer::TYPE_COLNAME => array (self::ID_SOLICITUD => 0, self::ID_SOLICITUD_TIPO => 1, self::PROGRAMA => 2, self::CURSO => 3, self::NOME_COMPLETO => 4, self::NUMERO_USO => 5, self::MINISTRANTE => 6, self::ORIENTADOR => 7, self::EMAIL => 8, self::MOTIVO_TRANCAMENTO => 9, self::NIVEL => 10, self::DATA_REALIZACAO => 11, self::HORARIO => 12, self::TITULO_TRABALHO => 13, self::NUMERO_PAGINAS => 14, self::SUGESTAO_BANCA => 15, self::CPF_DO_ALUNO => 16, self::TITULAR1 => 17, self::INSTITUCION1 => 18, self::ENDERECO1 => 19, self::TITULAR2 => 20, self::INSTITUCION2 => 21, self::ENDERECO2 => 22, self::ARQ_PLANO_TRABALHO => 23, self::ARQ_JUSTIFICATIVA => 24, self::ARQ_ORCAMENTO => 25, self::ARQ_CURRICULO_LATTED => 26, self::ARQ_PEDIDO_DO_INTERESSADO => 27, self::ARQ_CREDENCIAMENTO => 28, self::ARQ_PROF_EXTERNO => 29, self::ARQ_CADASTRO_DOCENTE_EXTERNO => 30, self::ARQ_CARTA_ALUNO => 31, self::ARQ_MANIFESTACAO_ORIENTADOR => 32, self::ARQ_CRONOGRAMA_ACTIVIDADES => 33, self::ARQ_COPIA_TRABALHO => 34, self::ARQ_COMPROBANTE => 35, self::ARQ_TRANSFERENCA_ORIENTACAO => 36, self::ARQ_TERMO_ORIENTADOR => 37, self::ARQ_RELATORIO_QUALIFICACAO => 38, self::ARQ_PROJETO_PESQUISA => 39, self::ARQ_SOLICITACAO_BOLSA => 40, self::STATUS => 41, ),
		BasePeer::TYPE_FIELDNAME => array ('id_solicitud' => 0, 'id_solicitud_tipo' => 1, 'programa' => 2, 'curso' => 3, 'nome_completo' => 4, 'numero_uso' => 5, 'ministrante' => 6, 'orientador' => 7, 'email' => 8, 'motivo_trancamento' => 9, 'nivel' => 10, 'data_realizacao' => 11, 'horario' => 12, 'titulo_trabalho' => 13, 'numero_paginas' => 14, 'sugestao_banca' => 15, 'cpf_do_aluno' => 16, 'titular1' => 17, 'institucion1' => 18, 'endereco1' => 19, 'titular2' => 20, 'institucion2' => 21, 'endereco2' => 22, 'arq_plano_trabalho' => 23, 'arq_justificativa' => 24, 'arq_orcamento' => 25, 'arq_curriculo_Latted' => 26, 'arq_pedido_do_interessado' => 27, 'arq_credenciamento' => 28, 'arq_prof_externo' => 29, 'arq_cadastro_docente_externo' => 30, 'arq_carta_aluno' => 31, 'arq_manifestacao_orientador' => 32, 'arq_cronograma_actividades' => 33, 'arq_copia_trabalho' => 34, 'arq_comprobante' => 35, 'arq_transferenca_orientacao' => 36, 'arq_termo_orientador' => 37, 'arq_relatorio_qualificacao' => 38, 'arq_projeto_pesquisa' => 39, 'arq_solicitacao_bolsa' => 40, 'status' => 41, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. SolicitudPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(SolicitudPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(SolicitudPeer::ID_SOLICITUD);
		$criteria->addSelectColumn(SolicitudPeer::ID_SOLICITUD_TIPO);
		$criteria->addSelectColumn(SolicitudPeer::PROGRAMA);
		$criteria->addSelectColumn(SolicitudPeer::CURSO);
		$criteria->addSelectColumn(SolicitudPeer::NOME_COMPLETO);
		$criteria->addSelectColumn(SolicitudPeer::NUMERO_USO);
		$criteria->addSelectColumn(SolicitudPeer::MINISTRANTE);
		$criteria->addSelectColumn(SolicitudPeer::ORIENTADOR);
		$criteria->addSelectColumn(SolicitudPeer::EMAIL);
		$criteria->addSelectColumn(SolicitudPeer::MOTIVO_TRANCAMENTO);
		$criteria->addSelectColumn(SolicitudPeer::NIVEL);
		$criteria->addSelectColumn(SolicitudPeer::DATA_REALIZACAO);
		$criteria->addSelectColumn(SolicitudPeer::HORARIO);
		$criteria->addSelectColumn(SolicitudPeer::TITULO_TRABALHO);
		$criteria->addSelectColumn(SolicitudPeer::NUMERO_PAGINAS);
		$criteria->addSelectColumn(SolicitudPeer::SUGESTAO_BANCA);
		$criteria->addSelectColumn(SolicitudPeer::CPF_DO_ALUNO);
		$criteria->addSelectColumn(SolicitudPeer::TITULAR1);
		$criteria->addSelectColumn(SolicitudPeer::INSTITUCION1);
		$criteria->addSelectColumn(SolicitudPeer::ENDERECO1);
		$criteria->addSelectColumn(SolicitudPeer::TITULAR2);
		$criteria->addSelectColumn(SolicitudPeer::INSTITUCION2);
		$criteria->addSelectColumn(SolicitudPeer::ENDERECO2);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_PLANO_TRABALHO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_JUSTIFICATIVA);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_ORCAMENTO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_CURRICULO_LATTED);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_PEDIDO_DO_INTERESSADO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_CREDENCIAMENTO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_PROF_EXTERNO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_CADASTRO_DOCENTE_EXTERNO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_CARTA_ALUNO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_MANIFESTACAO_ORIENTADOR);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_CRONOGRAMA_ACTIVIDADES);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_COPIA_TRABALHO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_COMPROBANTE);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_TRANSFERENCA_ORIENTACAO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_TERMO_ORIENTADOR);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_RELATORIO_QUALIFICACAO);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_PROJETO_PESQUISA);
		$criteria->addSelectColumn(SolicitudPeer::ARQ_SOLICITACAO_BOLSA);
		$criteria->addSelectColumn(SolicitudPeer::STATUS);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(SolicitudPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			SolicitudPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseSolicitudPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Solicitud
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = SolicitudPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return SolicitudPeer::populateObjects(SolicitudPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			SolicitudPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Solicitud $value A Solicitud object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Solicitud $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getIdSolicitud();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Solicitud object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Solicitud) {
				$key = (string) $value->getIdSolicitud();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Solicitud object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Solicitud Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to solicitud
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = SolicitudPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = SolicitudPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = SolicitudPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				SolicitudPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseSolicitudPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseSolicitudPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new SolicitudTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? SolicitudPeer::CLASS_DEFAULT : SolicitudPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Solicitud or Criteria object.
	 *
	 * @param      mixed $values Criteria or Solicitud object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseSolicitudPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseSolicitudPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Solicitud object
		}

		if ($criteria->containsKey(SolicitudPeer::ID_SOLICITUD) && $criteria->keyContainsValue(SolicitudPeer::ID_SOLICITUD) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.SolicitudPeer::ID_SOLICITUD.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseSolicitudPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseSolicitudPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Solicitud or Criteria object.
	 *
	 * @param      mixed $values Criteria or Solicitud object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseSolicitudPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseSolicitudPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(SolicitudPeer::ID_SOLICITUD);
			$selectCriteria->add(SolicitudPeer::ID_SOLICITUD, $criteria->remove(SolicitudPeer::ID_SOLICITUD), $comparison);

		} else { // $values is Solicitud object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseSolicitudPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseSolicitudPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the solicitud table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(SolicitudPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			SolicitudPeer::clearInstancePool();
			SolicitudPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Solicitud or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Solicitud object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			SolicitudPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Solicitud) { // it's a model object
			// invalidate the cache for this single object
			SolicitudPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(SolicitudPeer::ID_SOLICITUD, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				SolicitudPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			SolicitudPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Solicitud object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Solicitud $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Solicitud $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(SolicitudPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(SolicitudPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(SolicitudPeer::DATABASE_NAME, SolicitudPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Solicitud
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = SolicitudPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(SolicitudPeer::DATABASE_NAME);
		$criteria->add(SolicitudPeer::ID_SOLICITUD, $pk);

		$v = SolicitudPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(SolicitudPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(SolicitudPeer::DATABASE_NAME);
			$criteria->add(SolicitudPeer::ID_SOLICITUD, $pks, Criteria::IN);
			$objs = SolicitudPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseSolicitudPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseSolicitudPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseSolicitudPeer::buildTableMap();

