<?php


/**
 * This class defines the structure of the 'lojas' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 17/10/2013 16:31:46
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.geografia.map
 */
class LojasTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.geografia.map.LojasTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('lojas');
		$this->setPhpName('Lojas');
		$this->setClassname('Lojas');
		$this->setPackage('lib.model.geografia');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_LOJA', 'IdLoja', 'INTEGER', true, 11, null);
		$this->addColumn('ID_ESTADO', 'IdEstado', 'INTEGER', true, 11, null);
		$this->addColumn('ID_CIUDAD', 'IdCiudad', 'INTEGER', true, 11, null);
		$this->addColumn('TIPO_LOJA', 'TipoLoja', 'VARCHAR', true, 30, null);
		$this->addColumn('NOME_LOJA', 'NomeLoja', 'VARCHAR', true, 100, null);
		$this->addColumn('ENDERECO', 'Endereco', 'LONGVARCHAR', true, null, null);
		$this->addColumn('NUMERO', 'Numero', 'INTEGER', true, 11, null);
		$this->addColumn('COMPLEMENTO', 'Complemento', 'VARCHAR', true, 20, null);
		$this->addColumn('TELEFONE', 'Telefone', 'VARCHAR', true, 30, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', true, 30, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', true, 100, null);
		$this->addColumn('SITE', 'Site', 'VARCHAR', true, 100, null);
		$this->addColumn('STATUS', 'Status', 'INTEGER', true, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // LojasTableMap
