<?php


/**
 * This class defines the structure of the 'solicitud' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 17/10/2013 16:31:46
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.geografia.map
 */
class SolicitudTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.geografia.map.SolicitudTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('solicitud');
		$this->setPhpName('Solicitud');
		$this->setClassname('Solicitud');
		$this->setPackage('lib.model.geografia');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_SOLICITUD', 'IdSolicitud', 'INTEGER', true, 11, null);
		$this->addColumn('ID_SOLICITUD_TIPO', 'IdSolicitudTipo', 'INTEGER', true, 11, null);
		$this->addColumn('PROGRAMA', 'Programa', 'VARCHAR', true, 30, null);
		$this->addColumn('CURSO', 'Curso', 'VARCHAR', true, 30, null);
		$this->addColumn('NOME_COMPLETO', 'NomeCompleto', 'VARCHAR', true, 100, null);
		$this->addColumn('NUMERO_USO', 'NumeroUso', 'VARCHAR', true, 30, null);
		$this->addColumn('MINISTRANTE', 'Ministrante', 'VARCHAR', true, 30, null);
		$this->addColumn('ORIENTADOR', 'Orientador', 'VARCHAR', true, 50, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', true, 100, null);
		$this->addColumn('MOTIVO_TRANCAMENTO', 'MotivoTrancamento', 'VARCHAR', true, 50, null);
		$this->addColumn('NIVEL', 'Nivel', 'VARCHAR', true, 30, null);
		$this->addColumn('DATA_REALIZACAO', 'DataRealizacao', 'DATE', true, null, null);
		$this->addColumn('HORARIO', 'Horario', 'VARCHAR', true, 50, null);
		$this->addColumn('TITULO_TRABALHO', 'TituloTrabalho', 'VARCHAR', true, 150, null);
		$this->addColumn('NUMERO_PAGINAS', 'NumeroPaginas', 'VARCHAR', true, 50, null);
		$this->addColumn('SUGESTAO_BANCA', 'SugestaoBanca', 'VARCHAR', true, 50, null);
		$this->addColumn('CPF_DO_ALUNO', 'CpfDoAluno', 'VARCHAR', true, 50, null);
		$this->addColumn('TITULAR1', 'Titular1', 'VARCHAR', true, 150, null);
		$this->addColumn('INSTITUCION1', 'Institucion1', 'VARCHAR', true, 150, null);
		$this->addColumn('ENDERECO1', 'Endereco1', 'VARCHAR', true, 150, null);
		$this->addColumn('TITULAR2', 'Titular2', 'VARCHAR', true, 150, null);
		$this->addColumn('INSTITUCION2', 'Institucion2', 'VARCHAR', true, 150, null);
		$this->addColumn('ENDERECO2', 'Endereco2', 'VARCHAR', true, 150, null);
		$this->addColumn('ARQ_PLANO_TRABALHO', 'ArqPlanoTrabalho', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_JUSTIFICATIVA', 'ArqJustificativa', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_ORCAMENTO', 'ArqOrcamento', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_CURRICULO_LATTED', 'ArqCurriculoLatted', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_PEDIDO_DO_INTERESSADO', 'ArqPedidoDoInteressado', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_CREDENCIAMENTO', 'ArqCredenciamento', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_PROF_EXTERNO', 'ArqProfExterno', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_CADASTRO_DOCENTE_EXTERNO', 'ArqCadastroDocenteExterno', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_CARTA_ALUNO', 'ArqCartaAluno', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_MANIFESTACAO_ORIENTADOR', 'ArqManifestacaoOrientador', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_CRONOGRAMA_ACTIVIDADES', 'ArqCronogramaActividades', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_COPIA_TRABALHO', 'ArqCopiaTrabalho', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_COMPROBANTE', 'ArqComprobante', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_TRANSFERENCA_ORIENTACAO', 'ArqTransferencaOrientacao', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_TERMO_ORIENTADOR', 'ArqTermoOrientador', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_RELATORIO_QUALIFICACAO', 'ArqRelatorioQualificacao', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_PROJETO_PESQUISA', 'ArqProjetoPesquisa', 'VARCHAR', true, 100, null);
		$this->addColumn('ARQ_SOLICITACAO_BOLSA', 'ArqSolicitacaoBolsa', 'VARCHAR', true, 100, null);
		$this->addColumn('STATUS', 'Status', 'CHAR', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SolicitudTableMap
