<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/03/28 15:07:25
sfConfig::add(array(
  'app_name_app' => 'DEPARTAMENTO DE GEOGRAFIA - UNIVERSIDADE DE SÃO PAULO',
  'app_directory_productos' => '/var/www/html/ppgh/public_html/uploads/productos/',
  'app_allowed_mime_types_uploads' => array (
  0 => 'application/pdf',
),
  'app_email_administrador' => 'info@crismoe.com.br',
  'app_email_default_sender' => 'noresponder@crismoe.com.br',
  'app_msn_requerido' => 'Este campo é obrigatório',
  'app_msn_save_confir' => 'Registro salvo com sucesso',
  'app_msn_delete_confir' => 'Registro deletado com sucesso',
  'app_msn_perfil_confir' => 'Associado ao perfil de usuário',
  'app_image_help' => '<img  src="../images/help.png" align="left" />',
  'app_image_size' => 10485760,
  'app_image_size_text' => '10 MB',
  'app_image_size_max' => 3145728,
  'app_image_max_width' => 980,
  'app_image_min_width' => 980,
  'app_image_max_height' => 305,
  'app_image_min_height' => 280,
  'app_image_cantidad_maxima' => 12,
  'app_txt_size' => 2097152,
  'app_txt_size_text' => '2 MB',
  'app_txt_size_max' => 2097152,
  'app_pdf_help' => '<img  src="../images/help.png" align="left" />',
  'app_pdf_size' => 3145728,
  'app_pdf_size_text' => '250 Kb',
  'app_pdf_size_max' => 3145728,
  'app_upload_images_news' => array (
  'copies' => 4,
  'size_1' => 
  array (
    'pref_1' => 'big',
    'image_width_1' => 750,
    'image_height_1' => 563,
  ),
  'size_2' => 
  array (
    'pref_2' => 'medium',
    'image_width_2' => 464,
    'image_height_2' => 348,
  ),
  'size_3' => 
  array (
    'pref_3' => 'small',
    'image_width_3' => 232,
    'image_height_3' => 174,
  ),
  'size_4' => 
  array (
    'pref_4' => 'min',
    'image_width_4' => 84,
    'image_height_4' => 63,
  ),
),
  'app_upload_images_eventos' => array (
  'copies' => 4,
  'size_1' => 
  array (
    'pref_1' => 'big',
    'image_width_1' => 750,
    'image_height_1' => 563,
  ),
  'size_2' => 
  array (
    'pref_2' => 'medium',
    'image_width_2' => 464,
    'image_height_2' => 348,
  ),
  'size_3' => 
  array (
    'pref_3' => 'small',
    'image_width_3' => 232,
    'image_height_3' => 174,
  ),
  'size_4' => 
  array (
    'pref_4' => 'min',
    'image_width_4' => 84,
    'image_height_4' => 63,
  ),
),
  'app_upload_images_cliente' => array (
  'copies' => 1,
  'size_1' => 
  array (
    'pref_1' => 'cte',
    'image_width_1' => 150,
    'image_height_1' => 150,
  ),
),
  'app_upload_images_producto' => array (
  'copies' => 3,
  'size_1' => 
  array (
    'pref_1' => 'big',
    'image_width_1' => 392,
    'image_height_1' => 250,
  ),
  'size_2' => 
  array (
    'pref_2' => 'med',
    'image_width_2' => 196,
    'image_height_2' => 127,
  ),
  'size_3' => 
  array (
    'pref_3' => 'min',
    'image_width_3' => 140,
    'image_height_3' => 140,
  ),
),
  'app_upload_images_lxaccount' => array (
  'fileload' => 1,
  'copies' => 3,
  'size_1' => 
  array (
    'pref_1' => 'small',
    'image_width_1' => 28,
    'image_height_1' => 24,
  ),
  'size_2' => 
  array (
    'pref_2' => 'med',
    'image_width_2' => 52,
    'image_height_2' => 52,
  ),
  'size_3' => 
  array (
    'pref_3' => 'big',
    'image_width_3' => 94,
    'image_height_3' => 90,
  ),
),
  'app_upload_images_docente' => array (
  'fileload' => 1,
  'copies' => 3,
  'size_1' => 
  array (
    'pref_1' => 'small',
    'image_width_1' => 95,
    'image_height_1' => 60,
  ),
  'size_2' => 
  array (
    'pref_2' => 'med',
    'image_width_2' => 185,
    'image_height_2' => 170,
  ),
  'size_3' => 
  array (
    'pref_3' => 'big',
    'image_width_3' => 350,
    'image_height_3' => 315,
  ),
),
));
