<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/28 15:07:26

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=ppgh;host=localhost',
  'username' => 'root',
  'password' => 'mysqlPPGH01*2013',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
