<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/03/28 15:08:01
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'solicitudes_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'solicitudes_view',
      1 => 'solicitudes_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'solicitudes_view',
      1 => 'solicitudes_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'solicitudes_view',
      1 => 'solicitudes_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'solicitudes_view',
      1 => 'solicitudes_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'solicitudes_view',
      1 => 'solicitudes_delete',
    ),
  ),
);
