<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/04/02 10:34:23
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'formulario_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'formulario_view',
      1 => 'formulario_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'formulario_view',
      1 => 'formulario_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'formulario_view',
      1 => 'formulario_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'formulario_view',
      1 => 'formulario_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'formulario_view',
      1 => 'formulario_delete',
    ),
  ),
);
