<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/11 01:16:39
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_delete',
    ),
  ),
  'changestatus' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_update',
    ),
  ),
  'changeprivileges' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_profile_view',
      1 => 'lx_profile_update',
    ),
  ),
);
