<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/04/07 10:58:40
sfConfig::add(array(
  'mod_news_enabled' => true,
  'mod_news_view_class' => 'sfPHP',
  'mod_news_msn_ppal_permissions' => 'Núcleo habilitado a notícia',
  'mod_news_msn_no_permissions' => 'O núcleo selecionado não está habilitado',
));
