<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/11 01:15:23
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'tiposolicitud_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'tiposolicitud_view',
      1 => 'tiposolicitud_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'tiposolicitud_view',
      1 => 'tiposolicitud_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'tiposolicitud_view',
      1 => 'tiposolicitud_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'tiposolicitud_view',
      1 => 'tiposolicitud_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'tiposolicitud_view',
      1 => 'tiposolicitud_delete',
    ),
  ),
);
