<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/04/01 11:15:37
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'docente_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'docente_view',
      1 => 'docente_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'docente_view',
      1 => 'docente_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'docente_view',
      1 => 'docente_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'docente_view',
      1 => 'docente_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'docente_view',
      1 => 'docente_delete',
    ),
  ),
);
