<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/11 01:16:39
sfConfig::add(array(
  'mod_lxprofile_enabled' => true,
  'mod_lxprofile_view_class' => 'sfPHP',
  'mod_lxprofile_msn_ppal_permissions' => 'Selecione a opção de permissão na lista para atualizar os privilégios',
  'mod_lxprofile_msn_no_permissions' => 'You don\'t have the proper credentials to access this page',
));
