<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/03/31 16:08:46
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_update',
    ),
  ),
  'editcontent' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_update',
    ),
  ),
  'infolanguage' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_update',
    ),
  ),
  'treesections' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
    ),
  ),
  'listenermove' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'lx_section_view',
      1 => 'lx_section_delete',
    ),
  ),
);
