<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/04/16 15:38:57
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'disciplina_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'disciplina_view',
      1 => 'disciplina_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'disciplina_view',
      1 => 'disciplina_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'disciplina_view',
      1 => 'disciplina_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'disciplina_view',
      1 => 'disciplina_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'disciplina_view',
      1 => 'disciplina_delete',
    ),
  ),
);
