<?php


/**
 * Skeleton subclass for performing query and update operations on the 'banner_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 25/07/2013 10:02:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class BannerI18nPeer extends BaseBannerI18nPeer {
    
    public static function getBannersHome()
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias
        $c->addSelectColumn(self::ID_BANNER);
        $c->addSelectColumn(self::PREFIJO_NOME_BANNER);
        //Filtros        
        $c->add(self::STATUS, 1, Criteria::EQUAL);
        //Ejecucion de consulta
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $dato['id_banner']    = $res['ID_BANNER'];
            $dato['foto_banner']  = $res['PREFIJO_NOME_BANNER'];            
            $datos[] = $dato;
        }
        if(!empty($datos))
        {
            return $datos;
        }else{
            return false;
        }
    }

} // BannerI18nPeer
