<?php


/**
 * Skeleton subclass for representing a row from the 'banner_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 31/07/2013 11:27:47
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.geografia
 */
class BannerI18n extends BaseBannerI18n {

} // BannerI18n
