<?php


/**
 * Skeleton subclass for performing query and update operations on the 'caracteristica' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 14/08/2013 11:03:15
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.geografia
 */
class CaracteristicaPeer extends BaseCaracteristicaPeer {

} // CaracteristicaPeer
