<?php


/**
 * Skeleton subclass for representing a row from the 'ciudades' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 12/07/2013 15:52:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class Ciudades extends BaseCiudades {

} // Ciudades
