<?php


/**
 * Skeleton subclass for performing query and update operations on the 'ciudades' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 12/07/2013 15:52:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class CiudadesPeer extends BaseCiudadesPeer {
    
  public static function getCiudadesByEstado($id) {
    $c = new Criteria();
    $c->addAscendingOrderByColumn(self::NOME_CIUDAD);
    $c->add(self::ID_ESTADO, $id, Criteria::EQUAL);
    
    return self::doSelect($c);
  }

} // CiudadesPeer
