<?php


/**
 * Skeleton subclass for performing query and update operations on the 'corpo_docente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 21/07/2013 14:19:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class CorpoDocentePeer extends BaseCorpoDocentePeer {
    
    public static function getCorpoDocente()
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias
        $c->addSelectColumn(self::ID_DOCENTE);
        $c->addSelectColumn(self::NOME_DOCENTE);
        $c->addSelectColumn(self::RAMAL);
        $c->addSelectColumn(self::SALA);
        $c->addSelectColumn(self::SITE);
        $c->addSelectColumn(self::EMAIL);
        $c->addSelectColumn(self::CURRICULO);
        $c->addSelectColumn(self::PHOTO);
        //Ejecucion de consulta
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $dato['id_docente']     = $res['ID_DOCENTE'];
            $dato['nome_docente']   = $res['NOME_DOCENTE'];
            $dato['ramal']         = $res['RAMAL'];
            $dato['sala']          = $res['SALA'];
            $dato['site']          = $res['SITE'];
            $dato['email']          = $res['EMAIL'];
            $dato['curriculo']      = $res['CURRICULO'];
            $dato['photo']          = $res['PHOTO'];
            $datos[] = $dato;
        }
        if(!empty($datos))
        {
            return $datos;
        }else{
            return false;
        }
    }

} // CorpoDocentePeer
