<?php


/**
 * Skeleton subclass for representing a row from the 'eventos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 21/07/2013 15:10:34
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class Eventos extends BaseEventos {

} // Eventos
