<?php


/**
 * Skeleton subclass for representing a row from the 'linea_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 17/07/2013 17:04:34
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class LineaI18n extends BaseLineaI18n {

} // LineaI18n
