<?php


/**
 * Skeleton subclass for performing query and update operations on the 'linea' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 08/07/2013 06:25:58
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class LineaPeer extends BaseLineaPeer {
    
    public static function getAllLineas()
    {
        $c = new Criteria();
        return self::doSelect($c);
    }
    
    public static function getComboLineas()
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias
        $c->addSelectColumn(self::ID_LINEA);
        $c->addSelectColumn(self::NOME_LINEA);
        //Filtros        
        $c->addAscendingOrderByColumn(self::NOME_LINEA);
        //Ejecucion de consulta
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $datos[$res['ID_LINEA']] = $res['NOME_LINEA'];
        }
        if(!empty($datos)){
            return $datos;
        }else{
            return false;
        }
    }
    
        
    public static function getLineasByTipo($id) {
        $c = new Criteria();
        $c->addAscendingOrderByColumn(self::NOME_LINEA);
        $c->add(self::ID_TIPO, $id, Criteria::EQUAL);

        return self::doSelect($c);
    }

} // LineaPeer
