<?php


/**
 * Skeleton subclass for representing a row from the 'producto_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 16/07/2013 16:46:29
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class ProductoI18n extends BaseProductoI18n {

} // ProductoI18n
