<?php


/**
 * Skeleton subclass for performing query and update operations on the 'semestres' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 30/07/2013 11:23:39
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.geografia
 */
class SemestresPeer extends BaseSemestresPeer { 
    
    public static function validaNoRepeat($id, $sem, $ano)
    {
        $c = new Criteria();
        $c->add(self::SEMESTRE, $sem, Criteria::EQUAL);
        $c->add(self::ANO, $ano, Criteria::EQUAL);
        $c->add(self::ID_SEM, $id, Criteria::NOT_EQUAL);
        return self::doSelect($c) ;
    }
    
    public static function validaNoRepeatNews($sem, $ano)
    {
        $c = new Criteria();
        $c->add(self::SEMESTRE, $sem, Criteria::EQUAL);
        $c->add(self::ANO, $ano, Criteria::EQUAL);
        return self::doSelect($c) ;
    }
    
    public static function getSemestres()
    {
        $c = new Criteria();
        $c->addAscendingOrderByColumn(self::SEMESTRE);
        return self::doSelect($c) ;
    }
    
    public static function findSemestres()
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias
        $c->addSelectColumn(self::ID_SEM);
        $c->addSelectColumn(self::SEMESTRE);
        $c->addSelectColumn(self::ANO);
                
        $c->addAscendingOrderByColumn(self::ID_SEM);
        //Ejecucion de consulta
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        $sections[0] = 'None';
        while($res = $rs->fetch())
        {
            $sections[$res['ID_SEM']] = $res['SEMESTRE'].' - '.$res['ANO'];            
        }
        if(!empty($sections)){
            return $sections;
        }else{
            return false;
        }
    }

} // SemestresPeer
