<?php


/**
 * Skeleton subclass for representing a row from the 'solicitud_tipo_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/08/2013 15:36:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.geografia
 */
class SolicitudTipoI18n extends BaseSolicitudTipoI18n {

} // SolicitudTipoI18n
