<?php


/**
 * Skeleton subclass for performing query and update operations on the 'solicitud_tipo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 23/07/2013 11:15:26
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class SolicitudTipoPeer extends BaseSolicitudTipoPeer {
    
  public static function getTiposSolicitudes($lang)
  {
    //Obtengo el idioma principal
    $c = new Criteria();
    //Eliminamos la columnas de seleccion en caso de que esten definidas
    $c->clearSelectColumns();
    //Se Agregan las Columnas necesarias        
    $c->addSelectColumn(self::ID_SOLICITUD_TIPO);
    $c->addSelectColumn(SolicitudTipoI18nPeer::NOME_SOLICITUD);
    $c->addSelectColumn(SolicitudTipoI18nPeer::PERMALINK);
    $c->add(self::STATUS, '1', Criteria::EQUAL);
    $c->addJoin(self::ID_SOLICITUD_TIPO, SolicitudTipoI18nPeer::ID, Criteria::INNER_JOIN);
    $c->add(SolicitudTipoI18nPeer::LANGUAGE, $lang, Criteria::EQUAL);
    $rs = self::doSelectStmt($c);
    //Se recuperan los registros y se genera arreglo
    while($res = $rs->fetch())
    {
      $dato['id_tipo_solicitud'] = $res['ID_SOLICITUD_TIPO'];
      $dato['nome_tipo']        = $res['NOME_SOLICITUD'];
      $dato['permalink']        = $res['PERMALINK'];
      $datos[] = $dato;
    }

    if (!empty($datos)){
      return $datos;
    }else{
      return false;
    }
  }
  
  public static function getTipoByPermalink($permalink)
  {
      $c = new Criteria();
      $c->add(self::PERMALINK, $permalink, Criteria::EQUAL);
      return self::doSelectOne($c);
  }

} // SolicitudTipoPeer
