<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tipo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 08/07/2013 06:25:58
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class TipoPeer extends BaseTipoPeer {
    
            
    public static function getAllTipos()
    {
        $c = new Criteria();
        return self::doSelect($c);
    }
    
    public static function getComboTipos()
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias
        $c->addSelectColumn(self::ID_TIPO);
        $c->addSelectColumn(self::NOME_TIPO);
        //Filtros        
        $c->addAscendingOrderByColumn(self::NOME_TIPO);
        //Ejecucion de consulta
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $datos[$res['ID_TIPO']] = $res['NOME_TIPO'];
        }
        if(!empty($datos)){
            return $datos;
        }else{
            return false;
        }
    }
    
    public static function getTipoByCategoria($id) {
        $c = new Criteria();
        $c->addAscendingOrderByColumn(self::NOME_TIPO);
        $c->add(self::ID_CATEGORIA, $id, Criteria::EQUAL);

        return self::doSelect($c);
    }

} // TipoPeer
