<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tipo_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 17/07/2013 16:02:44
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.crismoe
 */
class TipoI18nPeer extends BaseTipoI18nPeer {
    
    public static function getNomeTipo($id_tipo, $lang="")
    {
        //Obtengo el idioma principal
        if(!$lang)
        {
            $idioma_principal = SfLanguagePeer::getLanguagePrincipal();
            $idioma_principal = $idioma_principal['language'];
        }else{
            $idioma_principal = $lang;
        }
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias        
        $c->addSelectColumn(self::NOME_TIPO);
        //Filtros
        $c->add(self::ID,$id_tipo, Criteria::EQUAL);
        $c->add(self::LANGUAGE, $idioma_principal ,Criteria::EQUAL);        
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $datoSeccion['nome_tipo'] = $res['NOME_TIPO'];
        }
        if (!empty($datoSeccion)){
            return $datoSeccion;
        }else{
            return false;
        }
    }

} // TipoI18nPeer
