<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/03/28 15:12:30
sfConfig::add(array(
  'app_namecompany' => 'DEPARTAMENTO DE GEOGRAFIA - UNIVERSIDADE DE SÃO PAULO',
  'app_nome_base_app' => 'DEPARTAMENTO DE GEOGRAFIA - UNIVERSIDADE DE SÃO PAULO',
  'app_email_administrator' => 'coordpgh@usp.br',
  'app_email_contato' => 'coordpgh@usp.br',
  'app_location_directory_album' => '/var/www/html/ppgh/public_html/uploads/albuns/',
  'app_location_dir_web_album' => '/uploads/albuns/',
  'app_msn_save_err' => 'Por favor, preencha os campos obrigatórios corretamente',
  'app_msn_save_confir' => 'Dados enviados com sucesso',
  'app_msn_save_confir_empresa' => 'Sua empresa foi registrada em nosso sistema com sucesso',
  'app_msn_no_resultados_op1' => 'Certifique-se de que todas as palavras estão escritas corretamente',
  'app_msn_no_resultados_op2' => 'Tente palavras-chave diferentes',
  'app_msn_no_resultados_op3' => 'Tente palavras-chave mais gerais',
  'app_base_dir_web' => '/',
));
