<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_news_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 02/08/2013 11:22:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.geografia
 */
class SfNewsI18nPeer extends BaseSfNewsI18nPeer {
    
    public static function getNomeNoticia($id, $lang)
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias        
        $c->addSelectColumn(self::TITLE);
        $c->addSelectColumn(self::SUMMARY);
        $c->addSelectColumn(self::BODY);
        //Filtros
        $c->add(self::ID,$id, Criteria::EQUAL);
        $c->add(self::LANGUAGE,$lang,Criteria::EQUAL);        
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $dato['titulo']          = $res['TITLE'];
            $dato['resumen']         = $res['SUMMARY'];
            $dato['descripcion']     = $res['BODY'];
        }
        if (!empty($dato)){
            return $dato;
        }else{
            return false;
        }
    }

    public static function deleita($id)
    {
        $con = Propel::getConnection();
	// select from...
	$c1 = new Criteria();
        $c1->add(self::ID, $id, Criteria::EQUAL);
	// delete
        BasePeer::doDelete($c1, $con);
    }
    
    public static function getBuscaNoticias($lang, $busca)
    {
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias        
        $c->addSelectColumn(self::TITLE);
        $c->addSelectColumn(self::BODY);
        $c->addSelectColumn(self::PERMALINK);
        //Filtros
        if($busca)
        {
            $criterio = $c->getNewCriterion(self::TITLE, '%'.$busca.'%', Criteria::LIKE);
            $criterio->addOr($c->getNewCriterion(self::BODY, '%'.$busca.'%', Criteria::LIKE));
            $c->add($criterio);
        }
        $c->add(self::LANGUAGE, $lang,Criteria::EQUAL);        
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $dato['titulo'] = $res['TITLE'];
            $dato['body']   = $res['BODY'];
            $dato['permalink']   = $res['PERMALINK'];
            $datos[] = $dato;
        }
        if (!empty($datos)){
            return $datos;
        }else{
            return false;
        }
    }

} // SfNewsI18nPeer
